components:
  schemas:
    LoginBody:
      properties:
        email:
          format: email
          type: string
        password:
          minLength: 6
          type: string
      required:
        - email
        - password
      type: object
info:
  title: Cryptocurrency API
  version: 1.0.0
openapi: 3.0.3
paths:
  /admin/users/{id}:
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted
      security:
        - cookieAuth: []
      summary: Delete user (admin)
  /auth/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginBody'
        required: true
      responses:
        '200':
          description: sets HttpOnly cookie
      summary: User login
  /coingecko/history/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: vs_currency
          required: true
          schema:
            type: string
        - in: query
          name: days
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
      summary: Coin history
  /users/me:
    delete:
      responses:
        '204':
          description: Deleted
      security:
        - cookieAuth: []
      summary: Delete own account
servers:
  - url: http://localhost:8080/api
